import os

MODEL = "claude-sonnet-4-6"

MAX_TOKENS_CHAT = 2048
MAX_TOKENS_MEMORY = 1024

HISTORY_PATH = "memory/history.json"
IDENTITY_PATH = "memory/identity.md"
SUMMARIES_PATH = "memory/summaries.json"
SCREEN_PNG_PATH = "memory/screen.png"

MAX_HISTORY_TURNS = 20
MAX_SUMMARIES = 10
IDENTITY_MAX_CHARS = 4000

SCREEN_SIZE = 320
SCREEN_FULLSCREEN = os.environ.get("SCREEN_FULLSCREEN", "true").lower() != "false"
EXPRESSION_INTERVAL_SECONDS = int(os.environ.get("EXPRESSION_INTERVAL_SECONDS", 30))
MAX_TOKENS_EXPRESSION = 512
EXPRESSION_HISTORY_WINDOW = 6
