MODEL = "claude-sonnet-4-6"

MAX_TOKENS_CHAT = 2048
MAX_TOKENS_MEMORY = 1024

HISTORY_PATH = "memory/history.json"
IDENTITY_PATH = "memory/identity.md"
SCREEN_PNG_PATH = "memory/screen.png"

MAX_HISTORY_TURNS = 50
IDENTITY_MAX_CHARS = 4000

SCREEN_SIZE = 320
EXPRESSION_INTERVAL_SECONDS = 30
MAX_TOKENS_EXPRESSION = 512
